# Generated by Django 5.2.7 on 2025-11-02 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = []
