# Generated by Django 5.2.7 on 2025-10-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_groups_alter_user_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                help_text="Введите номер телефона",
                unique=True,
                verbose_name="Номер телефона",
            ),
        ),
    ]
