# Generated by Django 5.2.7 on 2025-10-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="code",
            field=models.CharField(
                blank=True, max_length=4, null=True, verbose_name="Код авторизации"
            ),
        ),
    ]
