# Generated by Django 5.2.7 on 2025-11-01 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="code",
        ),
    ]
